### ISSUE TITLE
on the densest k-subgraph (DkS)

### ISSUE THREAD

**Issue by lancehaw** [c752334430/dsd_pip#1]
thanks for your good work! I am trying to find solution for the DkS problem, and find this library. Does the dsd library provides solution for the DkS problem? Any suggestions if I try to optimize the DkS problem based on the dsd library? Thanks!

**Comment by c752334430** [comment]
Hi, as you may know, DkS is not only hard to solve but also hard to approximate (reduction from max clique). So one easy heuristic is to run the peeling algorithm, i.e. iteratively remove node with the min degree, until there are k nodes left. This can be done with minor change in the greedy_helper_from_graph function of this repo.
See https://dl.acm.org/doi/abs/10.1145/1806689.1806719 if you want the best approximation guarantee.

**Comment by lancehaw** [comment]
thanks for your suggestion!
